Algoritmo "cálculo de tabuada"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/04/2024
Var
// Seção de Declarações das variáveis 
numero: inteiro
contagem: inteiro
resultado: inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("      ----------------------")
escreval("      { cálculo de tabuada } ")
escreval("      ----------------------")
escreval("")
escreval(" Olá pessoa que não conheço, seja bem vindo")
escreval(" qual número você deseja calcular")
leia(numero)
para contagem de 0 ate 10 passo 1 faca
 resultado <- contagem*numero
 escreval(contagem,"x",numero,"=",resultado)
fimpara
Fimalgoritmo