Algoritmo "cálculo de juros de um empréstimo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/04/2024
Var
// Seção de Declarações das variáveis 
valor: real
contagem: real
porcentagem: real
juros: real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("          Cálculo de Juros        ")
escreval("")
escreval("Olá, bem vindo ao cálculo de juros de um emprestimos")
escreval("Qual seria o valor desejado?")
escreval(valor)
 se () então
       escreval("")
     senao
      se () então
        escreval("")
      senao
       se () então
         escreval("")


        fimse
       fimse
      fimse
     fimse

       
Fimalgoritmo