Algoritmo "Programa de conversões"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2024
Var
   // Seção de Declarações das variáveis
   menu: inteiro
   dolar: real
   reais: real
   euro: real
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   escreval("     -------------------- ")
   escreval("     $Bem vindo Estranho$ ")
   escreval("     -------------------- ")
   escreval("")
   escreval("Digite a opcção que deseja")
   escreval("1 - conversor de moedas")
   escreval("2 - conversor de medidas")
   escreva("Opcção: ")
   leia(menu)

caso 1
   //Fazer um conversor de moedas
   escreval("Conversor de moedas")
   escreval("Informe qual moeda você deseja converter")
   escreval("Opcção: ")

   escreval("1 - Real")
   escreval("2 - Dolar")
   escreval("3 - Euro")
   escreva("Opcção: ")
   escolha menu

   fimescolha
Fimalgoritmo